---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished git pull --no-rebase
during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
Hello world

Prerequisites (12.1)

-Maya's Note:Completed (test repository on GitHub)

<<<<<<< HEAD
-Mahathi's Note: Completed (repo on Git)
=======
-Mahathi's Note: 
>>>>>>> fcd3e0287495c00489867db2c60f62db566c1d13

-Vaishnavi's Note: completed

Make a repo on GitHub (12.2)

-Maya's Note:Completed 

-Mahathi's Note: Completed (repo on Git)

-Vaishnavi's Note:


Clone the test GitHub repository to your computer via RStudio (12.3)

-Maya's Note: Worked

-Mahathi's Note: Completed (repo on Git)

-Vaishnavi's Note:


Make local changes, save, commit (12.4)

-Maya's Note: New local changes saved and completed.

-Mahathi's Note: Completed (repo on Git)

-Vaishnavi's Note:


Push your local changes online to GitHub (12.5)
<<<<<<< HEAD
=======

-Maya's Note: Completed
>>>>>>> 935524e (Organized and finished all problems.)

-Maya's Note: Completed
 
-Mahathi's Note: Completed (repo on Git)

-Vaishnavi's Note:


Confirm the local change propagated to the GitHub remote (12.6)

-Maya's Note:Confirmed 

-Mahathi's Note: Completed (repo on Git)

-Vaishnavi's Note:


Clean up (12.7)

-Maya's Note: Read instructions. okay.

-Mahathi's Note: Not supposed to complete

-Vaishnavi's Note:



